name: Publish Blogs
description: When pushing Zenn articles to GitHub, convert them to Qiita format and publish them.
author: Naoki Chihara

inputs:
  root:
    required: false
    default: "./qiita"
    description: "Root directory path"
  qiita-token:
    required: true
    description: "Qiita API token"
  convert-commit-message:
    required: false
    default: "Convert Zenn articles to Qiita format"
    description: "Commit message for converting Zenn articles to Qiita format"
  delete-commit-message:
    required: false
    default: "Delete Qiita articles"
    description: "Commit message for deleting Qiita articles"
  qiitacli-commit-message:
    required: false
    default: "Updated by qiita-cli"
    description: "Qiita commit message"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Get changed articles
      id: changed-articles
      uses: tj-actions/changed-files@v47
      with:
        files: articles/*.md
        since_last_remote_commit: true

    - name: Install qiita-cli
      if: steps.changed-articles.outputs.any_changed == 'true'
      run: |
        npm install @qiita/qiita-cli --save-dev
      shell: bash

    - name: Convert Zenn articles to Qiita format
      id: convert-articles
      if: steps.changed-articles.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-articles.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          filename=$(basename "$file" .md)
          echo "🚀 Convert $file to Qiita format"
          if [[ ! -f "qiita/public/$filename.md" ]]; then
              echo "🌱 Create new Qiita article"
              cd ./qiita
              npx qiita new "$filename"
              cd ../
            fi
            echo "🚚 Convert $file to qiita/public/$filename.md"
            node ${{ github.action_path }}/dist/index.js "$file" "./qiita/public/$filename.md"
        done
      shell: bash

    - name: Commit converted Qiita articles
      if: steps.convert-articles.outcome == 'success'
      run: |
        git config --local user.name ${{ github.actor }}
        git config --local user.email ${{ github.actor }}@users.noreply.github.com
        git add qiita/public/*.md
        git commit -m "${{ inputs.delete-commit-message }}"
        git push
      shell: bash

    - name: Delete Qiita articles
      id: delete-articles
      if: steps.changed-articles.outputs.any_deleted == 'true'
      env:
        DELETED_FILES: ${{ steps.changed-articles.outputs.deleted_files }}
      run: |
        for file in ${DELETED_FILES}; do
          filename=$(basename "$file" .md)
          qiita_file="qiita/public/$filename.md"
          if [[ -f "$qiita_file" ]]; then
            echo "🗑️ Delete $qiita_file"
            rm "$qiita_file"
          fi
        done
      shell: bash

    - name: Commit deleted Qiita articles
      if: steps.delete-articles.outcome == 'success'
      run: |
        git config --local user.name ${{ github.actor }}
        git config --local user.email ${{ github.actor }}@users.noreply.github.com
        git add -u qiita/public/
        git commit -m "${{ inputs.delete-commit-message }}"
        git push
      shell: bash

    - name: Publish Qiita articles
      if: steps.convert-articles.outcome == 'success'
      uses: increments/qiita-cli/actions/publish@v1
      with:
        qiita-token: ${{ inputs.qiita-token }}
        root: ${{ inputs.root }}
        commit-message: ${{ inputs.qiitacli-commit-message }}

branding:
  icon: refresh-cw
  color: green
